### ISSUE TITLE
unexpected device halt

### ISSUE THREAD

**Issue by gemesa** [bluewind-embedded-systems/bw-r-drivers-tc37x-examples#2]
I am experimenting with the tricore-probe, defmt logging and HighTec Rust Aurix compiler version 1.0.0, using the [BW blinky example](https://github.com/bluewind-embedded-systems/bw-r-drivers-tc37x-examples/tree/main/blinky) on a TC375 Lite Kit. I can build and run the firmware, but it halts abruptly after starting for some reason.

```
PS C:\Users\andra\git-repos\bw-r-drivers-tc37x-examples\blinky> cargo run
   Compiling blinky v0.1.0 (C:\Users\andra\git-repos\bw-r-drivers-tc37x-examples\blinky)
    Finished dev [unoptimized + debuginfo] target(s) in 0.59s
     Running `tricore-probe target\tc162-htc-none\debug\blinky.elf`
DEBUG power on reset
└─ bw_r_drivers_tc37x::ssw::tc0::init_clock @ C:\Users\andra\.cargo\registry\src\github.com-d2f9efa20490c5c8\bw-r-drivers-tc37x-0.2.0\src\ssw\tc0.rs:12
INFO  Wait for Duration { secs: 0, nanos: 500000000 }
└─ blinky::main @ src\main.rs:48
Device halted, backtrace as follows
0xAFFFC000 -> ??
└────────── @ ??:0
     0x0 -> ??
└────────── @ ??:0
```

Do you know what could be the issue?

I added this to `.cargo/config` (this is the only change I implemented):

```toml
[target.tc162-htc-none]
runner = "tricore-probe"
# Default dwarf version of v1.0.0 HighTec compiler is version 3 which is
# incompatible with defmt location information
rustflags = ["-Z", "dwarf-version=4"]

[build]
target = "tc162-htc-none"
```
